M48
; DRILL file {KiCad 9.0.7} date 2026-05-25T14:54:33+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-25T14:54:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C5.300
%
G90
G05
T1
X121.0Y-105.0
T2
X75.0Y-105.0
X113.0Y-43.0
X113.0Y-167.0
M30
