from scapy.all import Ether, IP, UDP, Raw, sendp

from ethernetSendHelperFunctions import normalize_payload
        

def ethernetSendPacket(INTERFACE:str=None, payload=None, count:int=1, inter:float=0.001, verbose:bool=False) -> None:
    # CHANGE INTERFACE to your Ethernet adapter name from the list generated by ethernetInterfaceChoises.py

    payload = normalize_payload(payload)
    if payload == None:
        return None

    packet = (
        Ether(
            dst="00:11:22:33:44:55",
            src="12:34:56:78:9A:BC",
            type=0x0800
        )
        / IP(
            src="192.168.1.10",
            dst="192.168.1.100"
        )
        / UDP(
            sport=5000,
            dport=1234
        )
        / payload
    )

    sendp(packet, iface=INTERFACE, count=count, inter=inter,verbose=verbose)

if __name__=='__main__':
    ethernetSendPacket()
    ethernetSendPacket("Ethernet 6", Raw(b"Hello FPGA UDP 1234"), verbose=True)
    ethernetSendPacket("Ethernet 6", "test 123456789, hello FPGA", count=3,verbose=True)
    ethernetSendPacket("Ethernet 6", [12,34,56,78,90], verbose=True)
    ethernetSendPacket("Ethernet 6", [120,340,560,780,900000], verbose=True)


