"""
Plot GUI-compatible sine payload TXT files.

This script reads TXT files generated by generate_sine_payload_txt.py.

Expected line format:

    hex:00 00 12 34 ...

Each line is treated as one UDP payload. The script concatenates all payloads,
decodes 16-bit samples, de-interleaves the channels, and plots the result.

Default data layout per time sample:

    channel 0 sample
    channel 1 sample
    ...
    channel 15 sample
    next time sample channel 0
    ...

Requires:
    pip install matplotlib
"""

import math
from pathlib import Path

import matplotlib.pyplot as plt


# ============================================================
# Easy-to-change settings
# ============================================================

INPUT_TXT_FILE = "sine_payloads.txt"

SAMPLE_RATE_HZ = 2_000_000
NUM_CHANNELS = 16

# "big" or "little" - must match the generator
ENDIANNESS = "big"

# "signed" or "unsigned" - must match the generator
SAMPLE_FORMAT = "unsigned"

# Plot only this many time samples.
# Set to None to plot the whole file.
MAX_TIME_SAMPLES_TO_PLOT = None

# Plot these channels.
# Examples:
#   [0]                 -> only channel 0
#   [0, 1, 2, 3]        -> first four channels
#   list(range(16))     -> all channels
CHANNELS_TO_PLOT = [0]

# Also save a PNG next to the txt file
SAVE_PNG = True


# ============================================================
# TXT parsing
# ============================================================

def parse_hex_line(line: str) -> bytes:
    line = line.strip()

    if not line:
        return b""

    lower = line.lower()

    if lower.startswith("hex:"):
        hex_text = line[4:].strip()
    elif lower.startswith("bytes:"):
        hex_text = line[6:].strip()
    else:
        raise ValueError(
            f"Unsupported line format:\n{line}\n\n"
            "This plotting script expects lines starting with 'hex:' or 'bytes:'."
        )

    hex_text = (
        hex_text
        .replace(",", " ")
        .replace("_", " ")
        .replace("\t", " ")
        .replace("\n", " ")
    )

    return bytes.fromhex(hex_text)


def read_payload_txt(file_path: str | Path) -> bytes:
    file_path = Path(file_path)

    all_data = bytearray()

    with file_path.open("r", encoding="utf-8-sig") as f:
        for line_number, line in enumerate(f, start=1):
            stripped = line.strip()

            if not stripped:
                continue

            try:
                all_data.extend(parse_hex_line(stripped))
            except Exception as e:
                raise ValueError(f"Error parsing line {line_number}: {e}")

    return bytes(all_data)


# ============================================================
# Sample decoding
# ============================================================

def decode_int16_samples(raw_data: bytes, endianness: str, sample_format: str) -> list[int]:
    if endianness not in ("big", "little"):
        raise ValueError("ENDIANNESS must be 'big' or 'little'")

    if sample_format not in ("signed", "unsigned"):
        raise ValueError("SAMPLE_FORMAT must be 'signed' or 'unsigned'")

    if len(raw_data) % 2 != 0:
        raise ValueError(f"Raw byte count is not even: {len(raw_data)} bytes")

    signed = sample_format == "signed"
    samples = []

    for i in range(0, len(raw_data), 2):
        samples.append(int.from_bytes(raw_data[i:i + 2], byteorder=endianness, signed=signed))

    return samples


def deinterleave_channels(samples: list[int], num_channels: int) -> list[list[int]]:
    if len(samples) % num_channels != 0:
        raise ValueError(
            f"Sample count {len(samples)} is not divisible by NUM_CHANNELS={num_channels}.\n"
            "Check NUM_CHANNELS and make sure the TXT file contains complete channel frames."
        )

    channel_data = [[] for _ in range(num_channels)]

    for frame_start in range(0, len(samples), num_channels):
        frame = samples[frame_start:frame_start + num_channels]

        for ch in range(num_channels):
            channel_data[ch].append(frame[ch])

    return channel_data


def make_time_axis(num_time_samples: int, sample_rate_hz: float) -> list[float]:
    return [n / sample_rate_hz for n in range(num_time_samples)]


# ============================================================
# Plotting
# ============================================================

def plot_channels(channel_data: list[list[int]], sample_rate_hz: float, channels_to_plot: list[int], max_samples=None):
    if not channel_data:
        raise ValueError("No channel data to plot")

    num_time_samples = len(channel_data[0])

    if max_samples is not None:
        num_time_samples = min(num_time_samples, max_samples)

    time_axis = make_time_axis(num_time_samples, sample_rate_hz)

    plt.figure()

    for ch in channels_to_plot:
        if ch < 0 or ch >= len(channel_data):
            raise ValueError(f"Invalid channel number: {ch}")

        plt.plot(time_axis, channel_data[ch][:num_time_samples], label=f"CH{ch}")

    plt.xlabel("Time [s]")
    plt.ylabel("Sample value")
    plt.title("Decoded TXT Payload Samples")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()


def main() -> None:
    input_file = Path(INPUT_TXT_FILE)

    raw_data = read_payload_txt(input_file)
    samples = decode_int16_samples(raw_data, ENDIANNESS, SAMPLE_FORMAT)
    channel_data = deinterleave_channels(samples, NUM_CHANNELS)

    total_time_samples = len(channel_data[0])
    duration_s = total_time_samples / SAMPLE_RATE_HZ

    print("Loaded:", input_file)
    print("Raw bytes:", len(raw_data))
    print("Total int16 samples:", len(samples))
    print("Channels:", NUM_CHANNELS)
    print("Time samples per channel:", total_time_samples)
    print("Duration [s]:", duration_s)
    print("Endianness:", ENDIANNESS)
    print("Sample format:", SAMPLE_FORMAT)
    print("Channels plotted:", CHANNELS_TO_PLOT)

    plot_channels(
        channel_data=channel_data,
        sample_rate_hz=SAMPLE_RATE_HZ,
        channels_to_plot=CHANNELS_TO_PLOT,
        max_samples=MAX_TIME_SAMPLES_TO_PLOT,
    )

    if SAVE_PNG:
        png_file = input_file.with_suffix(".png")
        plt.savefig(png_file, dpi=150)
        print("Saved plot:", png_file)

    plt.show()


if __name__ == "__main__":
    main()
