-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.1
-- Tue May 26 11:19:05 2026

-- parameterized module component declaration
component FIFOlg
    port (Data: in  std_logic_vector(7 downto 0); Clock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0); Empty: out  std_logic; 
        Full: out  std_logic; AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : FIFOlg
    port map (Data(7 downto 0)=>__, Clock=>__, WrEn=>__, RdEn=>__, Reset=>__, 
        Q(7 downto 0)=>__, Empty=>__, Full=>__, AlmostEmpty=>__, 
        AlmostFull=>__);
