-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.8
-- Wed May 27 11:46:23 2026

-- parameterized module component declaration
component DDR_RX
    port (clkin: in  std_logic; reset: in  std_logic; 
        sclk: out  std_logic; datain: in  std_logic_vector(4 downto 0); 
        q: out  std_logic_vector(9 downto 0));
end component;

-- parameterized module component instance
__ : DDR_RX
    port map (clkin=>__, reset=>__, sclk=>__, datain(4 downto 0)=>__, q(9 downto 0)=>__);
