-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.8
-- Tue May 19 13:28:33 2026

-- parameterized module component declaration
component DDR_forRGMII
    port (clkout: out  std_logic; refclk: in  std_logic; 
        reset: in  std_logic; data: in  std_logic_vector(9 downto 0); 
        dout: out  std_logic_vector(4 downto 0));
end component;

-- parameterized module component instance
__ : DDR_forRGMII
    port map (clkout=>__, refclk=>__, reset=>__, data(9 downto 0)=>__, 
        dout(4 downto 0)=>__);
