-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.8
--E:\Apps\Lattice Diamond\ispfpga\bin\nt64\scuba.exe -w -n DDR_Transmit -lang vhdl -synth lse -bus_exp 7 -bb -arch sa5p00m -type iol -mode Transmit -io_type LVCMOS25 -width 5 -freq_in 125 -gear 2 -aligned -del -1 

-- Wed May 27 11:25:18 2026

library IEEE;
use IEEE.std_logic_1164.all;
library ecp5um;
use ecp5um.components.all;

entity DDR_Transmit is
    port (
        clkout: out  std_logic; 
        refclk: in  std_logic; 
        reset: in  std_logic; 
        data: in  std_logic_vector(9 downto 0); 
        dout: out  std_logic_vector(4 downto 0));
end DDR_Transmit;

architecture Structure of DDR_Transmit is

    -- internal signal declarations
    signal db4: std_logic;
    signal da4: std_logic;
    signal db3: std_logic;
    signal da3: std_logic;
    signal db2: std_logic;
    signal da2: std_logic;
    signal db1: std_logic;
    signal da1: std_logic;
    signal db0: std_logic;
    signal da0: std_logic;
    signal scuba_vlo: std_logic;
    signal scuba_vhi: std_logic;
    signal sclk_t: std_logic;
    signal clkos: std_logic;
    signal clkop: std_logic;
    signal buf_clkout: std_logic;
    signal buf_douto4: std_logic;
    signal buf_douto3: std_logic;
    signal buf_douto2: std_logic;
    signal buf_douto1: std_logic;
    signal buf_douto0: std_logic;

    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst2_OB : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_OB4 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_OB3 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_OB2 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_OB1 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_OB0 : label is "LVCMOS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst4_ODDRX1F4: ODDRX1F
        port map (SCLK=>sclk_t, RST=>reset, D0=>da4, D1=>db4, 
            Q=>buf_douto4);

    Inst4_ODDRX1F3: ODDRX1F
        port map (SCLK=>sclk_t, RST=>reset, D0=>da3, D1=>db3, 
            Q=>buf_douto3);

    Inst4_ODDRX1F2: ODDRX1F
        port map (SCLK=>sclk_t, RST=>reset, D0=>da2, D1=>db2, 
            Q=>buf_douto2);

    Inst4_ODDRX1F1: ODDRX1F
        port map (SCLK=>sclk_t, RST=>reset, D0=>da1, D1=>db1, 
            Q=>buf_douto1);

    Inst4_ODDRX1F0: ODDRX1F
        port map (SCLK=>sclk_t, RST=>reset, D0=>da0, D1=>db0, 
            Q=>buf_douto0);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst3_ODDRX1F: ODDRX1F
        port map (SCLK=>clkos, RST=>reset, D0=>scuba_vhi, D1=>scuba_vlo, 
            Q=>buf_clkout);

    Inst2_OB: OB
        port map (I=>buf_clkout, O=>clkout);

    Inst1_OB4: OB
        port map (I=>buf_douto4, O=>dout(4));

    Inst1_OB3: OB
        port map (I=>buf_douto3, O=>dout(3));

    Inst1_OB2: OB
        port map (I=>buf_douto2, O=>dout(2));

    Inst1_OB1: OB
        port map (I=>buf_douto1, O=>dout(1));

    Inst1_OB0: OB
        port map (I=>buf_douto0, O=>dout(0));

    db4 <= data(9);
    db3 <= data(8);
    db2 <= data(7);
    db1 <= data(6);
    db0 <= data(5);
    da4 <= data(4);
    da3 <= data(3);
    da2 <= data(2);
    da1 <= data(1);
    da0 <= data(0);
    sclk_t <= clkop;
    clkos <= refclk;
    clkop <= refclk;
end Structure;
