-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.14.0.75.2
-- Module  Version: 5.8
--E:\Apps\Lattice Diamond\ispfpga\bin\nt64\scuba.exe -w -n DDR_Recieve -lang vhdl -synth lse -bus_exp 7 -bb -arch sa5p00m -type iol -mode Receive -io_type LVCMOS25 -width 5 -freq_in 125 -gear 2 -del 128 

-- Wed May 27 11:24:48 2026

library IEEE;
use IEEE.std_logic_1164.all;
library ecp5um;
use ecp5um.components.all;

entity DDR_Recieve is
    port (
        clkin: in  std_logic; 
        reset: in  std_logic; 
        sclk: out  std_logic; 
        datain: in  std_logic_vector(4 downto 0); 
        q: out  std_logic_vector(9 downto 0));
end DDR_Recieve;

architecture Structure of DDR_Recieve is

    -- internal signal declarations
    signal buf_clkin: std_logic;
    signal qb4: std_logic;
    signal qa4: std_logic;
    signal qb3: std_logic;
    signal qa3: std_logic;
    signal qb2: std_logic;
    signal qa2: std_logic;
    signal qb1: std_logic;
    signal qa1: std_logic;
    signal qb0: std_logic;
    signal qa0: std_logic;
    signal sclk_t: std_logic;
    signal dataini_t4: std_logic;
    signal dataini_t3: std_logic;
    signal dataini_t2: std_logic;
    signal dataini_t1: std_logic;
    signal dataini_t0: std_logic;
    signal buf_dataini4: std_logic;
    signal buf_dataini3: std_logic;
    signal buf_dataini2: std_logic;
    signal buf_dataini1: std_logic;
    signal buf_dataini0: std_logic;

    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst3_IB : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB4 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB3 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB2 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB1 : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_IB0 : label is "LVCMOS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst3_IB: IB
        port map (I=>clkin, O=>buf_clkin);

    Inst2_IDDRX1F4: IDDRX1F
        port map (D=>dataini_t4, SCLK=>sclk_t, RST=>reset, Q0=>qa4, 
            Q1=>qb4);

    Inst2_IDDRX1F3: IDDRX1F
        port map (D=>dataini_t3, SCLK=>sclk_t, RST=>reset, Q0=>qa3, 
            Q1=>qb3);

    Inst2_IDDRX1F2: IDDRX1F
        port map (D=>dataini_t2, SCLK=>sclk_t, RST=>reset, Q0=>qa2, 
            Q1=>qb2);

    Inst2_IDDRX1F1: IDDRX1F
        port map (D=>dataini_t1, SCLK=>sclk_t, RST=>reset, Q0=>qa1, 
            Q1=>qb1);

    Inst2_IDDRX1F0: IDDRX1F
        port map (D=>dataini_t0, SCLK=>sclk_t, RST=>reset, Q0=>qa0, 
            Q1=>qb0);

    udel_dataini4: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini4, Z=>dataini_t4);

    udel_dataini3: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini3, Z=>dataini_t3);

    udel_dataini2: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini2, Z=>dataini_t2);

    udel_dataini1: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini1, Z=>dataini_t1);

    udel_dataini0: DELAYG
        generic map (DEL_MODE=> "SCLK_CENTERED")
        port map (A=>buf_dataini0, Z=>dataini_t0);

    Inst1_IB4: IB
        port map (I=>datain(4), O=>buf_dataini4);

    Inst1_IB3: IB
        port map (I=>datain(3), O=>buf_dataini3);

    Inst1_IB2: IB
        port map (I=>datain(2), O=>buf_dataini2);

    Inst1_IB1: IB
        port map (I=>datain(1), O=>buf_dataini1);

    Inst1_IB0: IB
        port map (I=>datain(0), O=>buf_dataini0);

    sclk <= sclk_t;
    q(9) <= qb4;
    q(8) <= qb3;
    q(7) <= qb2;
    q(6) <= qb1;
    q(5) <= qb0;
    q(4) <= qa4;
    q(3) <= qa3;
    q(2) <= qa2;
    q(1) <= qa1;
    q(0) <= qa0;
    sclk_t <= buf_clkin;
end Structure;
